--DROP TABLE
CREATE TABLE CODELION (
	COL1	VARCHAR2(3),
	COL2	VARCHAR2(3)
);

SELECT * FROM CODELION;

INSERT INTO	CODELION VALUES	('AAA','BBB');
INSERT INTO	CODELION VALUES	('CCC','DDD');

COMMIT;

DROP TABLE CODELION;

SELECT * FROM CODELION;

--TRUNCATE TABLE
CREATE TABLE CODELION (
	COL1	VARCHAR2(3),
	COL2	VARCHAR2(3)
);

SELECT * FROM CODELION;

INSERT INTO	CODELION VALUES	('AAA','BBB');
INSERT INTO	CODELION VALUES	('CCC','DDD');

COMMIT;

TRUNCATE TABLE CODELION;

SELECT * FROM CODELION;
