SELECT * FROM NETFLIX n ;

UPDATE NETFLIX  SET VIEW_CNT =70 WHERE VIDEO_NAME ='나의 아저씨';
COMMIT;
SELECT * FROM NETFLIX n ;

UPDATE NETFLIX  SET CATAGORY ='드라마',REG_DATE =TO_DATE('20230101','YYYYMMDD')  WHERE VIDEO_NAME ='시그널';
COMMIT;
SELECT * FROM NETFLIX n ;

UPDATE NETFLIX  SET CATAGORY ='드라마',REG_DATE =TO_DATE('20230101','YYYYMMDD');
SELECT * FROM NETFLIX n ;
ROLLBACK;
SELECT * FROM NETFLIX n ;
