SELECT * FROM NETFLIX n ;

DELETE FROM NETFLIX n WHERE VIDEO_NAME ='미스터 쎤사인';
COMMIT;

SELECT * FROM NETFLIX n ;

DELETE FROM NETFLIX n WHERE CATAGORY ='드라마' AND VIEW_CNT <35;
ROLLBACK;

SELECT * FROM NETFLIX n ;

DELETE FROM NETFLIX n WHERE VIDEO_NAME IN ('나의 아저씨','시그널');
SELECT * FROM NETFLIX n ;

--TRUNCATE와 같은 효과
DELETE FROM NETFLIX n;
SELECT * FROM NETFLIX n ;
