--데이터 선택
SELECT * FROM NETFLIX n ;
SELECT VIDEO_NAME, CATAGORY FROM NETFLIX n ;

--조건문
SELECT * FROM NETFLIX n WHERE VIDEO_NAME ='나의 아저씨';
SELECT * FROM NETFLIX n WHERE VIDEO_NAME <>'나의 아저씨';

SELECT * FROM NETFLIX n WHERE VIEW_CNT < 50;
SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 30;

SELECT * FROM NETFLIX n WHERE REG_DATE  < SYSDATE-30;
SELECT * FROM NETFLIX n WHERE REG_DATE  < SYSDATE;

--중복제거
SELECT DISTINCT CATAGORY FROM NETFLIX n ;