--WHERE
SELECT * FROM NETFLIX n ;

--단일조건
SELECT * FROM NETFLIX n WHERE CATAGORY ='애니메이션';
SELECT * FROM NETFLIX n WHERE CATAGORY IN ('애니메이션', '영화');
SELECT * FROM NETFLIX n WHERE CATAGORY NOT IN ('애니메이션', '영화');

SELECT * FROM NETFLIX n WHERE VIEW_CNT < 70;
SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 70;

SELECT * FROM NETFLIX n WHERE REG_DATE  < TO_DATE('20230101','YYYYMMDD') ;

--다중조건
SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 70 AND CATAGORY ='애니메이션' ;
SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 70 AND REG_DATE  < TO_DATE('20230101','YYYYMMDD') ;

SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 70 OR CATAGORY ='애니메이션' ;
SELECT * FROM NETFLIX n WHERE VIEW_CNT <= 70 OR REG_DATE  < TO_DATE('20230101','YYYYMMDD') ;

--동일 칼럼 내 중복조건은 OR 또는 IN으로 필터링(VARCHAR2)
SELECT * FROM NETFLIX n WHERE CATAGORY ='애니메이션' OR CATAGORY ='영화' ;
SELECT * FROM NETFLIX n WHERE CATAGORY IN ('애니메이션', '영화');

--동일 칼럼 내 중복조건은 BETWEEN으로 필터링(NUMBER)
SELECT * FROM NETFLIX n WHERE VIEW_CNT >= 50 AND VIEW_CNT <= 70 ;
SELECT * FROM NETFLIX n WHERE VIEW_CNT BETWEEN 50 AND 70 ;


--LIKE
SELECT * FROM NETFLIX n WHERE VIDEO_NAME LIKE '미%';
SELECT * FROM NETFLIX n WHERE VIDEO_NAME LIKE '%인';
SELECT * FROM NETFLIX n WHERE VIDEO_NAME LIKE '%의%';