SELECT * FROM NETFLIX n ;

--GROUP BY
SELECT CATAGORY, COUNT(*) FROM NETFLIX n GROUP BY CATAGORY ;
SELECT CATAGORY, SUM(VIEW_CNT) FROM NETFLIX n GROUP BY CATAGORY ;
SELECT CATAGORY, MAX(VIEW_CNT) FROM NETFLIX n GROUP BY CATAGORY ORDER BY MAX(VIEW_CNT) DESC ;
SELECT CATAGORY, MIN(VIEW_CNT) FROM NETFLIX n GROUP BY CATAGORY ORDER BY MAX(VIEW_CNT) ;
SELECT CATAGORY, AVG(VIEW_CNT) FROM NETFLIX n GROUP BY CATAGORY ;

SELECT CATAGORY, MAX(VIEW_CNT),MIN(VIEW_CNT),AVG(VIEW_CNT) FROM NETFLIX n GROUP BY CATAGORY ORDER BY MAX(VIEW_CNT) DESC ;