SELECT * FROM NETFLIX n ;
SELECT * FROM NETFLIX_CAST nc ;

--LEFT OUTER JOIN
SELECT A.VIDEO_NAME, A.CATAGORY, B.CAST_MEMBER, B.BIRTHDAY 
  FROM NETFLIX A 
  LEFT OUTER JOIN NETFLIX_CAST B
  ON A.VIDEO_NAME = B.VIDEO_NAME ;

--INNER JOIN = LEFT OUTER JOIN을 같게(IN NOT NULL 활용)
--LEFT OUTER JOIN
 SELECT A.VIDEO_NAME, A.CATAGORY, B.CAST_MEMBER, B.BIRTHDAY 
  FROM NETFLIX A 
  LEFT OUTER JOIN NETFLIX_CAST B
  ON A.VIDEO_NAME = B.VIDEO_NAME
  WHERE B.CAST_MEMBER IS NOT NULL;
--INNER JOIN
SELECT A.VIDEO_NAME, A.CATAGORY, B.CAST_MEMBER, B.BIRTHDAY 
  FROM NETFLIX A, NETFLIX_CAST B
 WHERE A.VIDEO_NAME = B.VIDEO_NAME;