SELECT SYSDATE FROM	DUAL ; -- 현재 날짜, 시간

SELECT ADD_MONTHS(SYSDATE,3)  FROM	DUAL ; --3달 후
SELECT ADD_MONTHS(SYSDATE,-3) FROM	DUAL ; --3달 전

SELECT TRUNC(SYSDATE)	FROM DUAL ; --날짜만(시간미표현)

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM DUAL ; -- 표출방식
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL ; -- 표출방식
SELECT TO_CHAR(SYSDATE,'HH24:MI:SS') FROM DUAL ; -- 표출방식
