SELECT UPPER('Codelion') FROM DUAL ;
SELECT LOWER('Codelion') FROM DUAL ;

INSERT INTO CODELION VALUES	('hot','HOT');
INSERT INTO CODELION VALUES	('god','GOD');
INSERT INTO CODELION VALUES	('cat','CAT');
INSERT INTO CODELION VALUES	('dog','DOG');
COMMIT;

SELECT * FROM CODELION c ;

SELECT * FROM CODELION c  WHERE COL2 = UPPER('God');