/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : JOIN 복습(학습)
*/

-- MySQL
SELECT T1.CAR_ID,
    T1.CAR_TYPE,
    ROUND(T1.DAILY_FEE * 30 * (100 - T2.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS T1
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS T2
        ON T1.CAR_TYPE = T2.CAR_TYPE AND T2.DURATION_TYPE = '30일 이상'
WHERE T1.CAR_TYPE IN ('세단', 'SUV')
    AND T1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, T1.CAR_TYPE ASC, T1.CAR_ID DESC;

-- Oracle
SELECT *
FROM (SELECT CAR_ID, CAR_TYPE, (DAILY_FEE * (100 - DISCOUNT_RATE) * 30 / 100) FEE
     FROM CAR_RENTAL_COMPANY_CAR
     INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     USING (CAR_TYPE)
     WHERE DURATION_TYPE = '30일 이상')
WHERE CAR_TYPE in ('세단', 'SUV')
AND CAR_ID NOT IN (SELECT DISTINCT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE END_DATE >= TO_DATE('2022-11-01', 'yyyy-mm-dd')
              AND START_DATE <= TO_DATE('2022-11-30', 'yyyy-mm-dd'))
AND FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;