/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : JOIN 복습(학습)
*/

-- MySQL
SELECT ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
LEFT JOIN ANIMAL_INS INS USING (ANIMAL_ID)
WHERE  INS.DATETIME IS NULL
ORDER BY ANIMAL_ID;

-- Oracle
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS A
ON I.ANIMAL_ID = A.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID, A.NAME;