/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : Regexp_like 복습(학습)
*/

-- MySQL
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS AS INS
JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE != OUTS.SEX_UPON_OUTCOME
ORDER BY OUTS.ANIMAL_ID;

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY 1;

-- Oracle
SELECT I.ANIMAL_ID,I.ANIMAL_TYPE,I.NAME
from ANIMAL_INS I inner join ANIMAL_OUTS O
on I.ANIMAL_ID = O.ANIMAL_ID
where I.SEX_UPON_INTAKE LIKE 'Intact%'
and  Regexp_like(O.SEX_UPON_OUTCOME,'^Spayed|^Neutered');

