/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit, https://jaehwaseo.tistory.com/8
□ 목적 : ROUND, AVG, HAVING 복습(학습)
*/

-- MySQL
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)) + 1, 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

-- Oracle
SELECT CAR_ID, ROUND(AVG(DIF),1) AS AVERAGE_DURATION
FROM (
      SELECT CAR_ID, START_DATE, END_DATE, (END_DATE - START_DATE + 1) AS DIF
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      )
GROUP BY CAR_ID
HAVING ROUND(AVG(DIF),1) > 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
