/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit, https://jaehwaseo.tistory.com/8
□ 목적 : JOIN, AND 복습(학습)
*/

-- MySQL
SELECT A.APNT_NO ,P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
LEFT JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
LEFT JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD="CS" AND DATE_FORMAT(A.APNT_YMD ,'%Y-%m-%d') ='2022-04-13' AND A.APNT_CNCL_YN ='N'
ORDER BY A.APNT_YMD;

-- Oracle
SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, C.DR_NAME , B.APNT_YMD
FROM PATIENT A, APPOINTMENT B, DOCTOR C
WHERE 1=1
AND A.PT_NO = B.PT_NO
AND C.DR_ID = B.MDDR_ID
AND C.MCDP_CD = 'CS'
AND TO_CHAR(B.APNT_YMD,'YYYYMMDD')='20220413'
AND B.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;
