/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : DATE_FORMAT, TO_CHAR 복습(학습)
*/

-- MySQL
SELECT HISTORY_ID ,
CASE WHEN DIFF < 7 THEN ROUND(DAILY_FEE * DIFF)
     WHEN DIFF < 30 THEN ROUND(DAILY_FEE * 0.95 * DIFF)
     WHEN DIFF < 90 THEN ROUND(DAILY_FEE * 0.92 * DIFF)
     ELSE  ROUND(DAILY_FEE * 0.85 * DIFF) END FEE

FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') C
INNER JOIN (SELECT  *, DATEDIFF(END_DATE, START_DATE)+1 DIFF FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H
ON C.CAR_ID = H.CAR_ID
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;

-- Oracle
SELECT A.HISTORY_ID, B.DAILY_FEE*(A.END_DATE-A.START_DATE+1) * NVL(1-DISCOUNT_RATE/100,1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON B.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = (CASE WHEN (A.END_DATE-A.START_DATE+1)>='90' THEN '90일 이상'
                            WHEN (A.END_DATE-A.START_DATE+1)>='30' THEN '30일 이상'
                            WHEN (A.END_DATE-A.START_DATE+1)>='7' THEN '7일 이상'
                            ELSE NULL END)
WHERE 1=1
AND B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC;
