/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : Equi Join 복습(학습)
*/

-- MySQL
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AS AI, ANIMAL_OUTS AS AO
WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY ABS(DATEDIFF(AI.DATETIME, AO.DATETIME)) DESC
LIMIT 2;

-- Oracle
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI, ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY ABS(AO.DATETIME - AI.DATETIME) DESC
FETCH FIRST 2 ROW ONLY;