/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : SUBSTR 복습(학습)
*/

-- MySQL
SELECT LEFT(PRODUCT_CODE, 2) AS "CATEGORY", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY CATEGORY
-- GROUP BY SUBSTR(PRODUCT_CODE,1,2)
-- GROUP BY LEFT(PRODUCT_CODE, 2)
ORDER BY CATEGORY ASC;

-- Oracle
SELECT SUBSTR(PRODUCT_CODE,1,2) AS "CATEGORY", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE,1,2)
ORDER BY CATEGORY ASC;