/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : SELECT 복습(학습)
*/

-- MySQL
SELECT A.FLAVOR
  FROM FIRST_HALF A, ICECREAM_INFO B
  WHERE (A.FLAVOR = B.FLAVOR) AND (A.TOTAL_ORDER > 3000 AND B.INGREDIENT_TYPE = 'fruit_based')
  ORDER BY TOTAL_ORDER DESC;

-- Oracle
SELECT A.FLAVOR
    FROM FIRST_HALF A, ICECREAM_INFO B
    WHERE (A.FLAVOR=B.FLAVOR) AND (A.TOTAL_ORDER>3000 AND B.INGREDIENT_TYPE='fruit_based')
    ORDER BY TOTAL_ORDER DESC;