/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : SELECT 복습(학습)
*/

-- MySQL
SELECT DR_NAME,DR_ID,MCDP_CD,DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS "HIRE_YMD"
FROM DOCTOR
WHERE MCDP_CD='CS' OR MCDP_CD='GS'
-- WHERE MCDP_CD='CS' OR MCDP_CD='GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC;

-- Oracle
SELECT DR_NAME,DR_ID,MCDP_CD,TO_CHAR(HIRE_YMD, 'YYYY-MM-DD') AS "HIRE_YMD"
FROM DOCTOR
-- WHERE MCDP_CD='CS' OR MCDP_CD='GS'
WHERE MCDP_CD in ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;