/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : SELECT 복습(학습)
*/

-- MySQL
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
       DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d')
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y%m') = 202210
      AND B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE, B.TITLE ASC;

-- Oracle
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS,
       TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS "CREATED_DATE"
from USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
    on A.BOARD_ID = B.BOARD_ID
where TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
order by B.CREATED_DATE , A.TITLE ASC;