/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : SELECT 복습(학습)
*/

-- MySQL
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS "PUBLISHED_DATE"
FROM BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE,'%Y')='2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;

-- Oracle
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') AS "PUBLISHED_DATE"
FROM BOOK
WHERE TO_CHAR(PUBLISHED_DATE,'YYYY')='2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;