/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : GROUP BY 복습(학습)
*/

-- MySQL
SELECT CAR_TYPE, COUNT(CAR_ID) AS "CARS"
FROM CAR_RENTAL_COMPANY_CAR
-- WHERE OPTIONS LIKE '%시트%'
-- WHERE REGEXP_LIKE(OPTIONS, '통풍시트|열선시트|가죽시트')
WHERE OPTIONS REGEXP ('통풍시트|열선시트|가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;

-- Oracle
SELECT CAR_TYPE, COUNT(CAR_ID) AS "CARS"
FROM CAR_RENTAL_COMPANY_CAR
-- WHERE OPTIONS LIKE '%시트%'
WHERE REGEXP_LIKE(OPTIONS, '통풍시트|열선시트|가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;