/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : GROUP BY 복습(학습)
*/

-- MySQL
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
    (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
    )
AND START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH ASC, CAR_ID DESC;

-- Oracle
SSELECT MONTH, CAR_ID, RECORDS
FROM
    (
    SELECT MONTH, CAR_ID,
           COUNT(CAR_ID) OVER (PARTITION BY MONTH, CAR_ID) AS RECORDS,
           COUNT(CAR_ID) OVER (PARTITION BY CAR_ID) AS ALL_RECORDS
    FROM
        (
        SELECT HISTORY_ID, TO_NUMBER(LTRIM(TO_CHAR(START_DATE,'MM'),'0')) AS MONTH,
               CAR_ID, START_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= TO_DATE('20220801','YYYY-MM-DD')
        )
         )
WHERE ALL_RECORDS >= 5
GROUP BY MONTH, CAR_ID, RECORDS
ORDER BY MONTH, CAR_ID DESC;