/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : GROUP BY, JOIN 복습(학습)
*/

-- MySQL
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BS
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = BS.BOOK_ID
AND BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;

-- Oracle
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES*BOOK.PRICE) AS TOTAL_SALE
FROM BOOK
INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE TO_CHAR(BOOK_SALES.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;