/*
□ 참고 : https://school.programmers.co.kr/learn/challenges?tab=sql_practice_kit
□ 목적 : GROUP BY 복습(학습)
*/

-- MySQL
SELECT (PRICE DIV 10000) * 10000 AS "PRICE_GROUP", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;

SELECT FLOOR(PRICE / 10000) * 10000 AS "PRICE_GORUP", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY FLOOR(PRICE / 10000) * 10000
ORDER BY FLOOR(PRICE / 10000) * 10000

-- Oracle
SELECT SUBSTR(PRICE, 1, 1) * 10000 AS "PRICE_GROUP", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY SUBSTR(PRICE, 1, 1) * 10000
ORDER BY PRICE_GROUP;

SELECT TRUNC(PRICE, -4) AS "PRICE_GROUP", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY TRUNC(PRICE, -4)
ORDER BY PRICE_GROUP ASC;